### ISSUE TITLE
Конфиги в репозитории

### ISSUE THREAD

**Issue by RagunovichVlad** [ErmolkinVlad/ad_service#10]
Конфигов не должно быть в репозитории по 2 причинам:

1. это небезопасно, если в них хранятся пароли для production-сервера;
2. это неудобно, если разработчикам нужно изменять конфиг у себя локально (например, изменять имя пользователя бд).

С конфигами поступают так:

1. добавляют примеры в config/examples;
2. удаляют сами конфиги из репозитория;
3. добавляют их в .gitignore, чтобы никто случайно не закомитил.

**Comment by ErmolkinVlad** [comment]
1. добавляют примеры в config/examples;
Можешь пояснить? Добавлять те же файлы, только с "example" паролями в папку config/examples?

**Comment by RagunovichVlad** [comment]
да, только еще удали ключи например здесь https://github.com/ErmolkinVlad/ad_service/blob/master/config/cloudinary.yml

```
development:
  cloud_name:
  api_key: 
  api_secret:
  enhance_image_tag: true
  static_image_support: false
```
или так
```
development:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key:  <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
```
